# Generated by Django 3.1.4 on 2021-08-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='upload',
        ),
    ]
