# Generated by Django 3.1.4 on 2021-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
