# Generated by Django 3.1.4 on 2021-08-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210804_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(default='not upadated', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='not updated', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(default='static/images/heart.png', upload_to='uploads'),
        ),
    ]
