# Generated by Django 3.1.4 on 2021-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210809_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
